<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->char('iso', 2);
            $table->string('name');
            $table->string('nicename');
            $table->char('iso3', 3);
            $table->integer('numcode');
            $table->integer('phone_code');
        });

        //Add all countries to the database
        DB::table('countries')->insert([
            [
                'id' => '1',
                'iso' => 'AF',
                'name' => 'AFGHANISTAN',
                'nicename' => 'Afghanistan',
                'iso3' => 'AFG',
                'numcode' => '4',
                'phone_code' => '93',
            ],
            [
                'id' => '2',
                'iso' => 'AL',
                'name' => 'ALBANIA',
                'nicename' => 'Albania',
                'iso3' => 'ALB',
                'numcode' => '8',
                'phone_code' => '355',
             ],
             [ 
             
                'id' => '3',
                'iso' => 'DZ',
                'name' => 'ALGERIA',
                'nicename' => 'Algeria',
                'iso3' => 'DZA',
                'numcode' => '12',
                'phone_code' => '213',
             ],
             [ 
             
                'id' => '4',
                'iso' => 'AS',
                'name' => 'AMERICAN SAMOA',
                'nicename' => 'American Samoa',
                'iso3' => 'ASM',
                'numcode' => '16',
                'phone_code' => '1684',
             ],
             [ 
             
                'id' => '5',
                'iso' => 'AD',
                'name' => 'ANDORRA',
                'nicename' => 'Andorra',
                'iso3' => 'AND',
                'numcode' => '20',
                'phone_code' => '376',
             ],
             [ 
             
                'id' => '6',
                'iso' => 'AO',
                'name' => 'ANGOLA',
                'nicename' => 'Angola',
                'iso3' => 'AGO',
                'numcode' => '24',
                'phone_code' => '244',
             ],
             [ 
             
                'id' => '7',
                'iso' => 'AI',
                'name' => 'ANGUILLA',
                'nicename' => 'Anguilla',
                'iso3' => 'AIA',
                'numcode' => '660',
                'phone_code' => '1264',
             ],
             [ 
             
                'id' => '8',
                'iso' => 'AQ',
                'name' => 'ANTARCTICA',
                'nicename' => 'Antarctica',
                'iso3' => 'ATA',
                'numcode' => '010',
                'phone_code' => '0',
             ],
             [ 
             
                'id' => '9',
                'iso' => 'AG',
                'name' => 'ANTIGUA AND BARBUDA',
                'nicename' => 'Antigua and Barbuda',
                'iso3' => 'ATG',
                'numcode' => '28',
                'phone_code' => '1268',
             ],
             [ 
             
                'id' => '10',
                'iso' => 'AR',
                'name' => 'ARGENTINA',
                'nicename' => 'Argentina',
                'iso3' => 'ARG',
                'numcode' => '32',
                'phone_code' => '54',
             ],
             [ 
             
                'id' => '11',
                'iso' => 'AM',
                'name' => 'ARMENIA',
                'nicename' => 'Armenia',
                'iso3' => 'ARM',
                'numcode' => '51',
                'phone_code' => '374',
             ],
             [ 
             
                'id' => '12',
                'iso' => 'AW',
                'name' => 'ARUBA',
                'nicename' => 'Aruba',
                'iso3' => 'ABW',
                'numcode' => '533',
                'phone_code' => '297',
             ],
             [ 
             
                'id' => '13',
                'iso' => 'AU',
                'name' => 'AUSTRALIA',
                'nicename' => 'Australia',
                'iso3' => 'AUS',
                'numcode' => '36',
                'phone_code' => '61',
             ],
             [ 
             
                'id' => '14',
                'iso' => 'AT',
                'name' => 'AUSTRIA',
                'nicename' => 'Austria',
                'iso3' => 'AUT',
                'numcode' => '40',
                'phone_code' => '43',
             ],
             [ 
             
                'id' => '15',
                'iso' => 'AZ',
                'name' => 'AZERBAIJAN',
                'nicename' => 'Azerbaijan',
                'iso3' => 'AZE',
                'numcode' => '31',
                'phone_code' => '994',
             ],
             [ 
             
                'id' => '16',
                'iso' => 'BS',
                'name' => 'BAHAMAS',
                'nicename' => 'Bahamas',
                'iso3' => 'BHS',
                'numcode' => '44',
                'phone_code' => '1242',
             ],
             [ 
             
                'id' => '17',
                'iso' => 'BH',
                'name' => 'BAHRAIN',
                'nicename' => 'Bahrain',
                'iso3' => 'BHR',
                'numcode' => '48',
                'phone_code' => '973',
             ],
             [ 
             
                'id' => '18',
                'iso' => 'BD',
                'name' => 'BANGLADESH',
                'nicename' => 'Bangladesh',
                'iso3' => 'BGD',
                'numcode' => '50',
                'phone_code' => '880',
             ],
             [ 
             
                'id' => '19',
                'iso' => 'BB',
                'name' => 'BARBADOS',
                'nicename' => 'Barbados',
                'iso3' => 'BRB',
                'numcode' => '52',
                'phone_code' => '1246',
             ],
             [ 
             
                'id' => '20',
                'iso' => 'BY',
                'name' => 'BELARUS',
                'nicename' => 'Belarus',
                'iso3' => 'BLR',
                'numcode' => '112',
                'phone_code' => '375',
             ],
             [ 
             
                'id' => '21',
                'iso' => 'BE',
                'name' => 'BELGIUM',
                'nicename' => 'Belgium',
                'iso3' => 'BEL',
                'numcode' => '56',
                'phone_code' => '32',
             ],
             [ 
             
                'id' => '22',
                'iso' => 'BZ',
                'name' => 'BELIZE',
                'nicename' => 'Belize',
                'iso3' => 'BLZ',
                'numcode' => '84',
                'phone_code' => '501',
             ],
             [ 
             
                'id' => '23',
                'iso' => 'BJ',
                'name' => 'BENIN',
                'nicename' => 'Benin',
                'iso3' => 'BEN',
                'numcode' => '204',
                'phone_code' => '229',
             ],
             [ 
             
                'id' => '24',
                'iso' => 'BM',
                'name' => 'BERMUDA',
                'nicename' => 'Bermuda',
                'iso3' => 'BMU',
                'numcode' => '60',
                'phone_code' => '1441',
             ],
             [ 
             
                'id' => '25',
                'iso' => 'BT',
                'name' => 'BHUTAN',
                'nicename' => 'Bhutan',
                'iso3' => 'BTN',
                'numcode' => '64',
                'phone_code' => '975',
             ],
             [ 
             
                'id' => '26',
                'iso' => 'BO',
                'name' => 'BOLIVIA',
                'nicename' => 'Bolivia',
                'iso3' => 'BOL',
                'numcode' => '68',
                'phone_code' => '591',
             ],
             [ 
             
                'id' => '27',
                'iso' => 'BA',
                'name' => 'BOSNIA AND HERZEGOVINA',
                'nicename' => 'Bosnia and Herzegovina',
                'iso3' => 'BIH',
                'numcode' => '70',
                'phone_code' => '387',
             ],
             [ 
             
                'id' => '28',
                'iso' => 'BW',
                'name' => 'BOTSWANA',
                'nicename' => 'Botswana',
                'iso3' => 'BWA',
                'numcode' => '72',
                'phone_code' => '267',
             ],
             [ 
             
                'id' => '29',
                'iso' => 'BV',
                'name' => 'BOUVET ISLAND',
                'nicename' => 'Bouvet Island',
                'iso3' => 'BVT',
                'numcode' => '074',
                'phone_code' => '0',
             ],
             [ 
             
                'id' => '30',
                'iso' => 'BR',
                'name' => 'BRAZIL',
                'nicename' => 'Brazil',
                'iso3' => 'BRA',
                'numcode' => '76',
                'phone_code' => '55',
             ],
             [ 
             
                'id' => '31',
                'iso' => 'IO',
                'name' => 'BRITISH INDIAN OCEAN TERRITORY',
                'nicename' => 'British Indian Ocean Territory',
                'iso3' => 'IOT',
                'numcode' => '086',
                'phone_code' => '246',
             ],
             [ 
             
                'id' => '32',
                'iso' => 'BN',
                'name' => 'BRUNEI DARUSSALAM',
                'nicename' => 'Brunei Darussalam',
                'iso3' => 'BRN',
                'numcode' => '96',
                'phone_code' => '673',
             ],
             [ 
             
                'id' => '33',
                'iso' => 'BG',
                'name' => 'BULGARIA',
                'nicename' => 'Bulgaria',
                'iso3' => 'BGR',
                'numcode' => '100',
                'phone_code' => '359',
             ],
             [ 
             
                'id' => '34',
                'iso' => 'BF',
                'name' => 'BURKINA FASO',
                'nicename' => 'Burkina Faso',
                'iso3' => 'BFA',
                'numcode' => '854',
                'phone_code' => '226',
             ],
             [ 
             
                'id' => '35',
                'iso' => 'BI',
                'name' => 'BURUNDI',
                'nicename' => 'Burundi',
                'iso3' => 'BDI',
                'numcode' => '108',
                'phone_code' => '257',
             ],
             [ 
             
                'id' => '36',
                'iso' => 'KH',
                'name' => 'CAMBODIA',
                'nicename' => 'Cambodia',
                'iso3' => 'KHM',
                'numcode' => '116',
                'phone_code' => '855',
             ],
             [ 
             
                'id' => '37',
                'iso' => 'CM',
                'name' => 'CAMEROON',
                'nicename' => 'Cameroon',
                'iso3' => 'CMR',
                'numcode' => '120',
                'phone_code' => '237',
             ],
             [ 
             
                'id' => '38',
                'iso' => 'CA',
                'name' => 'CANADA',
                'nicename' => 'Canada',
                'iso3' => 'CAN',
                'numcode' => '124',
                'phone_code' => '1',
             ],
             [ 
             
                'id' => '39',
                'iso' => 'CV',
                'name' => 'CAPE VERDE',
                'nicename' => 'Cape Verde',
                'iso3' => 'CPV',
                'numcode' => '132',
                'phone_code' => '238',
             ],
             [ 
             
                'id' => '40',
                'iso' => 'KY',
                'name' => 'CAYMAN ISLANDS',
                'nicename' => 'Cayman Islands',
                'iso3' => 'CYM',
                'numcode' => '136',
                'phone_code' => '1345',
             ],
             [ 
             
                'id' => '41',
                'iso' => 'CF',
                'name' => 'CENTRAL AFRICAN REPUBLIC',
                'nicename' => 'Central African Republic',
                'iso3' => 'CAF',
                'numcode' => '140',
                'phone_code' => '236',
             ],
             [ 
             
                'id' => '42',
                'iso' => 'TD',
                'name' => 'CHAD',
                'nicename' => 'Chad',
                'iso3' => 'TCD',
                'numcode' => '148',
                'phone_code' => '235',
             ],
             [ 
             
                'id' => '43',
                'iso' => 'CL',
                'name' => 'CHILE',
                'nicename' => 'Chile',
                'iso3' => 'CHL',
                'numcode' => '152',
                'phone_code' => '56',
             ],
             [ 
             
                'id' => '44',
                'iso' => 'CN',
                'name' => 'CHINA',
                'nicename' => 'China',
                'iso3' => 'CHN',
                'numcode' => '156',
                'phone_code' => '86',
             ],
             [ 
             
                'id' => '45',
                'iso' => 'CX',
                'name' => 'CHRISTMAS ISLAND',
                'nicename' => 'Christmas Island',
                'iso3' => 'CXR',
                'numcode' => '162',
                'phone_code' => '61',
             ],
             [ 
             
                'id' => '46',
                'iso' => 'CC',
                'name' => 'COCOS (KEELING) ISLANDS',
                'nicename' => 'Cocos (Keeling) Islands',
                'iso3' => 'CCK',
                'numcode' => '166',
                'phone_code' => '672',
             ],
             [ 
             
                'id' => '47',
                'iso' => 'CO',
                'name' => 'COLOMBIA',
                'nicename' => 'Colombia',
                'iso3' => 'COL',
                'numcode' => '170',
                'phone_code' => '57',
             ],
             [ 
             
                'id' => '48',
                'iso' => 'KM',
                'name' => 'COMOROS',
                'nicename' => 'Comoros',
                'iso3' => 'COM',
                'numcode' => '174',
                'phone_code' => '269',
             ],
             [ 
             
                'id' => '49',
                'iso' => 'CG',
                'name' => 'CONGO',
                'nicename' => 'Congo',
                'iso3' => 'COG',
                'numcode' => '178',
                'phone_code' => '242',
             ],
             [ 
             
                'id' => '50',
                'iso' => 'CD',
                'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE',
                'nicename' => 'Congo, the Democratic Republic of the',
                'iso3' => 'COD',
                'numcode' => '180',
                'phone_code' => '242',
             ],
             [ 
             
                'id' => '51',
                'iso' => 'CK',
                'name' => 'COOK ISLANDS',
                'nicename' => 'Cook Islands',
                'iso3' => 'COK',
                'numcode' => '184',
                'phone_code' => '682',
             ],
             [ 
             
                'id' => '52',
                'iso' => 'CR',
                'name' => 'COSTA RICA',
                'nicename' => 'Costa Rica',
                'iso3' => 'CRI',
                'numcode' => '188',
                'phone_code' => '506',
             ],
             [ 
             
                'id' => '53',
                'iso' => 'CI',
                'name' => 'COTE D\'IVOIRE',
                'nicename' => 'Cote D\'Ivoire',
                'iso3' => 'CIV',
                'numcode' => '384',
                'phone_code' => '225',
             ],
             [ 
             
                'id' => '54',
                'iso' => 'HR',
                'name' => 'CROATIA',
                'nicename' => 'Croatia',
                'iso3' => 'HRV',
                'numcode' => '191',
                'phone_code' => '385',
             ],
             [ 
             
                'id' => '55',
                'iso' => 'CU',
                'name' => 'CUBA',
                'nicename' => 'Cuba',
                'iso3' => 'CUB',
                'numcode' => '192',
                'phone_code' => '53',
             ],
             [ 
             
                'id' => '56',
                'iso' => 'CY',
                'name' => 'CYPRUS',
                'nicename' => 'Cyprus',
                'iso3' => 'CYP',
                'numcode' => '196',
                'phone_code' => '357',
             ],
             [ 
             
                'id' => '57',
                'iso' => 'CZ',
                'name' => 'CZECH REPUBLIC',
                'nicename' => 'Czech Republic',
                'iso3' => 'CZE',
                'numcode' => '203',
                'phone_code' => '420',
             ],
             [ 
             
                'id' => '58',
                'iso' => 'DK',
                'name' => 'DENMARK',
                'nicename' => 'Denmark',
                'iso3' => 'DNK',
                'numcode' => '208',
                'phone_code' => '45',
             ],
             [ 
             
                'id' => '59',
                'iso' => 'DJ',
                'name' => 'DJIBOUTI',
                'nicename' => 'Djibouti',
                'iso3' => 'DJI',
                'numcode' => '262',
                'phone_code' => '253',
             ],
             [ 
             
                'id' => '60',
                'iso' => 'DM',
                'name' => 'DOMINICA',
                'nicename' => 'Dominica',
                'iso3' => 'DMA',
                'numcode' => '212',
                'phone_code' => '1767',
             ],
             [ 
             
                'id' => '61',
                'iso' => 'DO',
                'name' => 'DOMINICAN REPUBLIC',
                'nicename' => 'Dominican Republic',
                'iso3' => 'DOM',
                'numcode' => '214',
                'phone_code' => '1809',
             ],
             [ 
             
                'id' => '62',
                'iso' => 'EC',
                'name' => 'ECUADOR',
                'nicename' => 'Ecuador',
                'iso3' => 'ECU',
                'numcode' => '218',
                'phone_code' => '593',
             ],
             [ 
             
                'id' => '63',
                'iso' => 'EG',
                'name' => 'EGYPT',
                'nicename' => 'Egypt',
                'iso3' => 'EGY',
                'numcode' => '818',
                'phone_code' => '20',
             ],
             [ 
             
                'id' => '64',
                'iso' => 'SV',
                'name' => 'EL SALVADOR',
                'nicename' => 'El Salvador',
                'iso3' => 'SLV',
                'numcode' => '222',
                'phone_code' => '503',
             ],
             [ 
             
                'id' => '65',
                'iso' => 'GQ',
                'name' => 'EQUATORIAL GUINEA',
                'nicename' => 'Equatorial Guinea',
                'iso3' => 'GNQ',
                'numcode' => '226',
                'phone_code' => '240',
             ],
             [ 
             
                'id' => '66',
                'iso' => 'ER',
                'name' => 'ERITREA',
                'nicename' => 'Eritrea',
                'iso3' => 'ERI',
                'numcode' => '232',
                'phone_code' => '291',
             ],
             [ 
             
                'id' => '67',
                'iso' => 'EE',
                'name' => 'ESTONIA',
                'nicename' => 'Estonia',
                'iso3' => 'EST',
                'numcode' => '233',
                'phone_code' => '372',
             ],
             [ 
             
                'id' => '68',
                'iso' => 'ET',
                'name' => 'ETHIOPIA',
                'nicename' => 'Ethiopia',
                'iso3' => 'ETH',
                'numcode' => '231',
                'phone_code' => '251',
             ],
             [ 
             
                'id' => '69',
                'iso' => 'FK',
                'name' => 'FALKLAND ISLANDS (MALVINAS)',
                'nicename' => 'Falkland Islands (Malvinas)',
                'iso3' => 'FLK',
                'numcode' => '238',
                'phone_code' => '500',
             ],
             [ 
             
                'id' => '70',
                'iso' => 'FO',
                'name' => 'FAROE ISLANDS',
                'nicename' => 'Faroe Islands',
                'iso3' => 'FRO',
                'numcode' => '234',
                'phone_code' => '298',
             ],
             [ 
             
                'id' => '71',
                'iso' => 'FJ',
                'name' => 'FIJI',
                'nicename' => 'Fiji',
                'iso3' => 'FJI',
                'numcode' => '242',
                'phone_code' => '679',
             ],
             [ 
             
                'id' => '72',
                'iso' => 'FI',
                'name' => 'FINLAND',
                'nicename' => 'Finland',
                'iso3' => 'FIN',
                'numcode' => '246',
                'phone_code' => '358',
             ],
             [ 
             
                'id' => '73',
                'iso' => 'FR',
                'name' => 'FRANCE',
                'nicename' => 'France',
                'iso3' => 'FRA',
                'numcode' => '250',
                'phone_code' => '33',
             ],
             [ 
             
                'id' => '74',
                'iso' => 'GF',
                'name' => 'FRENCH GUIANA',
                'nicename' => 'French Guiana',
                'iso3' => 'GUF',
                'numcode' => '254',
                'phone_code' => '594',
             ],
             [ 
             
                'id' => '75',
                'iso' => 'PF',
                'name' => 'FRENCH POLYNESIA',
                'nicename' => 'French Polynesia',
                'iso3' => 'PYF',
                'numcode' => '258',
                'phone_code' => '689',
             ],
             [ 
             
                'id' => '76',
                'iso' => 'TF',
                'name' => 'FRENCH SOUTHERN TERRITORIES',
                'nicename' => 'French Southern Territories',
                'iso3' => 'ATF',
                'numcode' => '260',
                'phone_code' => '0',
             ],
             [ 
             
                'id' => '77',
                'iso' => 'GA',
                'name' => 'GABON',
                'nicename' => 'Gabon',
                'iso3' => 'GAB',
                'numcode' => '266',
                'phone_code' => '241',
             ],
             [ 
             
                'id' => '78',
                'iso' => 'GM',
                'name' => 'GAMBIA',
                'nicename' => 'Gambia',
                'iso3' => 'GMB',
                'numcode' => '270',
                'phone_code' => '220',
             ],
             [ 
             
                'id' => '79',
                'iso' => 'GE',
                'name' => 'GEORGIA',
                'nicename' => 'Georgia',
                'iso3' => 'GEO',
                'numcode' => '268',
                'phone_code' => '995',
             ],
             [ 
             
                'id' => '80',
                'iso' => 'DE',
                'name' => 'GERMANY',
                'nicename' => 'Germany',
                'iso3' => 'DEU',
                'numcode' => '276',
                'phone_code' => '49',
             ],
             [ 
             
                'id' => '81',
                'iso' => 'GH',
                'name' => 'GHANA',
                'nicename' => 'Ghana',
                'iso3' => 'GHA',
                'numcode' => '288',
                'phone_code' => '233',
             ],
             [ 
             
                'id' => '82',
                'iso' => 'GI',
                'name' => 'GIBRALTAR',
                'nicename' => 'Gibraltar',
                'iso3' => 'GIB',
                'numcode' => '292',
                'phone_code' => '350',
             ],
             [ 
             
                'id' => '83',
                'iso' => 'GR',
                'name' => 'GREECE',
                'nicename' => 'Greece',
                'iso3' => 'GRC',
                'numcode' => '300',
                'phone_code' => '30',
             ],
             [ 
             
                'id' => '84',
                'iso' => 'GL',
                'name' => 'GREENLAND',
                'nicename' => 'Greenland',
                'iso3' => 'GRL',
                'numcode' => '304',
                'phone_code' => '299',
             ],
             [ 
             
                'id' => '85',
                'iso' => 'GD',
                'name' => 'GRENADA',
                'nicename' => 'Grenada',
                'iso3' => 'GRD',
                'numcode' => '308',
                'phone_code' => '1473',
             ],
             [ 
             
                'id' => '86',
                'iso' => 'GP',
                'name' => 'GUADELOUPE',
                'nicename' => 'Guadeloupe',
                'iso3' => 'GLP',
                'numcode' => '312',
                'phone_code' => '590',
             ],
             [ 
             
                'id' => '87',
                'iso' => 'GU',
                'name' => 'GUAM',
                'nicename' => 'Guam',
                'iso3' => 'GUM',
                'numcode' => '316',
                'phone_code' => '1671',
             ],
             [ 
             
                'id' => '88',
                'iso' => 'GT',
                'name' => 'GUATEMALA',
                'nicename' => 'Guatemala',
                'iso3' => 'GTM',
                'numcode' => '320',
                'phone_code' => '502',
             ],
             [ 
             
                'id' => '89',
                'iso' => 'GN',
                'name' => 'GUINEA',
                'nicename' => 'Guinea',
                'iso3' => 'GIN',
                'numcode' => '324',
                'phone_code' => '224',
             ],
             [ 
             
                'id' => '90',
                'iso' => 'GW',
                'name' => 'GUINEA-BISSAU',
                'nicename' => 'Guinea-Bissau',
                'iso3' => 'GNB',
                'numcode' => '624',
                'phone_code' => '245',
             ],
             [ 
             
                'id' => '91',
                'iso' => 'GY',
                'name' => 'GUYANA',
                'nicename' => 'Guyana',
                'iso3' => 'GUY',
                'numcode' => '328',
                'phone_code' => '592',
             ],
             [ 
             
                'id' => '92',
                'iso' => 'HT',
                'name' => 'HAITI',
                'nicename' => 'Haiti',
                'iso3' => 'HTI',
                'numcode' => '332',
                'phone_code' => '509',
             ],
             [ 
             
                'id' => '93',
                'iso' => 'HM',
                'name' => 'HEARD ISLAND AND MCDONALD ISLANDS',
                'nicename' => 'Heard Island and Mcdonald Islands',
                'iso3' => 'HMD',
                'numcode' => '334',
                'phone_code' => '0',
             ],
             [ 
             
                'id' => '94',
                'iso' => 'VA',
                'name' => 'HOLY SEE (VATICAN CITY STATE)',
                'nicename' => 'Holy See (Vatican City State)',
                'iso3' => 'VAT',
                'numcode' => '336',
                'phone_code' => '39',
             ],
             [ 
             
                'id' => '95',
                'iso' => 'HN',
                'name' => 'HONDURAS',
                'nicename' => 'Honduras',
                'iso3' => 'HND',
                'numcode' => '340',
                'phone_code' => '504',
             ],
             [ 
             
                'id' => '96',
                'iso' => 'HK',
                'name' => 'HONG KONG',
                'nicename' => 'Hong Kong',
                'iso3' => 'HKG',
                'numcode' => '344',
                'phone_code' => '852',
             ],
             [ 
             
                'id' => '97',
                'iso' => 'HU',
                'name' => 'HUNGARY',
                'nicename' => 'Hungary',
                'iso3' => 'HUN',
                'numcode' => '348',
                'phone_code' => '36',
             ],
             [ 
             
                'id' => '98',
                'iso' => 'IS',
                'name' => 'ICELAND',
                'nicename' => 'Iceland',
                'iso3' => 'ISL',
                'numcode' => '352',
                'phone_code' => '354',
             ],
             [ 
             
                'id' => '99',
                'iso' => 'IN',
                'name' => 'INDIA',
                'nicename' => 'India',
                'iso3' => 'IND',
                'numcode' => '356',
                'phone_code' => '91',
             ],
             [ 
             
                'id' => '100',
                'iso' => 'ID',
                'name' => 'INDONESIA',
                'nicename' => 'Indonesia',
                'iso3' => 'IDN',
                'numcode' => '360',
                'phone_code' => '62',
             ],
             [ 
             
                'id' => '101',
                'iso' => 'IR',
                'name' => 'IRAN, ISLAMIC REPUBLIC OF',
                'nicename' => 'Iran, Islamic Republic of',
                'iso3' => 'IRN',
                'numcode' => '364',
                'phone_code' => '98',
             ],
             [ 
             
                'id' => '102',
                'iso' => 'IQ',
                'name' => 'IRAQ',
                'nicename' => 'Iraq',
                'iso3' => 'IRQ',
                'numcode' => '368',
                'phone_code' => '964',
             ],
             [ 
             
                'id' => '103',
                'iso' => 'IE',
                'name' => 'IRELAND',
                'nicename' => 'Ireland',
                'iso3' => 'IRL',
                'numcode' => '372',
                'phone_code' => '353',
             ],
             [ 
             
                'id' => '104',
                'iso' => 'IL',
                'name' => 'ISRAEL',
                'nicename' => 'Israel',
                'iso3' => 'ISR',
                'numcode' => '376',
                'phone_code' => '972',
             ],
             [ 
             
                'id' => '105',
                'iso' => 'IT',
                'name' => 'ITALY',
                'nicename' => 'Italy',
                'iso3' => 'ITA',
                'numcode' => '380',
                'phone_code' => '39',
             ],
             [ 
             
                'id' => '106',
                'iso' => 'JM',
                'name' => 'JAMAICA',
                'nicename' => 'Jamaica',
                'iso3' => 'JAM',
                'numcode' => '388',
                'phone_code' => '1876',
             ],
             [ 
             
                'id' => '107',
                'iso' => 'JP',
                'name' => 'JAPAN',
                'nicename' => 'Japan',
                'iso3' => 'JPN',
                'numcode' => '392',
                'phone_code' => '81',
             ],
             [ 
             
                'id' => '108',
                'iso' => 'JO',
                'name' => 'JORDAN',
                'nicename' => 'Jordan',
                'iso3' => 'JOR',
                'numcode' => '400',
                'phone_code' => '962',
             ],
             [ 
             
                'id' => '109',
                'iso' => 'KZ',
                'name' => 'KAZAKHSTAN',
                'nicename' => 'Kazakhstan',
                'iso3' => 'KAZ',
                'numcode' => '398',
                'phone_code' => '7',
             ],
             [ 
             
                'id' => '110',
                'iso' => 'KE',
                'name' => 'KENYA',
                'nicename' => 'Kenya',
                'iso3' => 'KEN',
                'numcode' => '404',
                'phone_code' => '254',
             ],
             [ 
             
                'id' => '111',
                'iso' => 'KI',
                'name' => 'KIRIBATI',
                'nicename' => 'Kiribati',
                'iso3' => 'KIR',
                'numcode' => '296',
                'phone_code' => '686',
             ],
             [ 
             
                'id' => '112',
                'iso' => 'KP',
                'name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF',
                'nicename' => 'Korea, Democratic People\'s Republic of',
                'iso3' => 'PRK',
                'numcode' => '408',
                'phone_code' => '850',
             ],
             [ 
             
                'id' => '113',
                'iso' => 'KR',
                'name' => 'KOREA, REPUBLIC OF',
                'nicename' => 'Korea, Republic of',
                'iso3' => 'KOR',
                'numcode' => '410',
                'phone_code' => '82',
             ],
             [ 
             
                'id' => '114',
                'iso' => 'KW',
                'name' => 'KUWAIT',
                'nicename' => 'Kuwait',
                'iso3' => 'KWT',
                'numcode' => '414',
                'phone_code' => '965',
             ],
             [ 
             
                'id' => '115',
                'iso' => 'KG',
                'name' => 'KYRGYZSTAN',
                'nicename' => 'Kyrgyzstan',
                'iso3' => 'KGZ',
                'numcode' => '417',
                'phone_code' => '996',
             ],
             [ 
             
                'id' => '116',
                'iso' => 'LA',
                'name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
                'nicename' => 'Lao People\'s Democratic Republic',
                'iso3' => 'LAO',
                'numcode' => '418',
                'phone_code' => '856',
             ],
             [ 
             
                'id' => '117',
                'iso' => 'LV',
                'name' => 'LATVIA',
                'nicename' => 'Latvia',
                'iso3' => 'LVA',
                'numcode' => '428',
                'phone_code' => '371',
             ],
             [ 
             
                'id' => '118',
                'iso' => 'LB',
                'name' => 'LEBANON',
                'nicename' => 'Lebanon',
                'iso3' => 'LBN',
                'numcode' => '422',
                'phone_code' => '961',
             ],
             [ 
             
                'id' => '119',
                'iso' => 'LS',
                'name' => 'LESOTHO',
                'nicename' => 'Lesotho',
                'iso3' => 'LSO',
                'numcode' => '426',
                'phone_code' => '266',
             ],
             [ 
             
                'id' => '120',
                'iso' => 'LR',
                'name' => 'LIBERIA',
                'nicename' => 'Liberia',
                'iso3' => 'LBR',
                'numcode' => '430',
                'phone_code' => '231',
             ],
             [ 
             
                'id' => '121',
                'iso' => 'LY',
                'name' => 'LIBYAN ARAB JAMAHIRIYA',
                'nicename' => 'Libyan Arab Jamahiriya',
                'iso3' => 'LBY',
                'numcode' => '434',
                'phone_code' => '218',
             ],
             [ 
             
                'id' => '122',
                'iso' => 'LI',
                'name' => 'LIECHTENSTEIN',
                'nicename' => 'Liechtenstein',
                'iso3' => 'LIE',
                'numcode' => '438',
                'phone_code' => '423',
             ],
             [ 
             
                'id' => '123',
                'iso' => 'LT',
                'name' => 'LITHUANIA',
                'nicename' => 'Lithuania',
                'iso3' => 'LTU',
                'numcode' => '440',
                'phone_code' => '370',
             ],
             [ 
             
                'id' => '124',
                'iso' => 'LU',
                'name' => 'LUXEMBOURG',
                'nicename' => 'Luxembourg',
                'iso3' => 'LUX',
                'numcode' => '442',
                'phone_code' => '352',
             ],
             [ 
             
                'id' => '125',
                'iso' => 'MO',
                'name' => 'MACAO',
                'nicename' => 'Macao',
                'iso3' => 'MAC',
                'numcode' => '446',
                'phone_code' => '853',
             ],
             [ 
             
                'id' => '126',
                'iso' => 'MK',
                'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
                'nicename' => 'Macedonia, the Former Yugoslav Republic of',
                'iso3' => 'MKD',
                'numcode' => '807',
                'phone_code' => '389',
             ],
             [ 
             
                'id' => '127',
                'iso' => 'MG',
                'name' => 'MADAGASCAR',
                'nicename' => 'Madagascar',
                'iso3' => 'MDG',
                'numcode' => '450',
                'phone_code' => '261',
             ],
             [ 
             
                'id' => '128',
                'iso' => 'MW',
                'name' => 'MALAWI',
                'nicename' => 'Malawi',
                'iso3' => 'MWI',
                'numcode' => '454',
                'phone_code' => '265',
             ],
             [ 
             
                'id' => '129',
                'iso' => 'MY',
                'name' => 'MALAYSIA',
                'nicename' => 'Malaysia',
                'iso3' => 'MYS',
                'numcode' => '458',
                'phone_code' => '60',
             ],
             [ 
             
                'id' => '130',
                'iso' => 'MV',
                'name' => 'MALDIVES',
                'nicename' => 'Maldives',
                'iso3' => 'MDV',
                'numcode' => '462',
                'phone_code' => '960',
             ],
             [ 
             
                'id' => '131',
                'iso' => 'ML',
                'name' => 'MALI',
                'nicename' => 'Mali',
                'iso3' => 'MLI',
                'numcode' => '466',
                'phone_code' => '223',
             ],
             [ 
             
                'id' => '132',
                'iso' => 'MT',
                'name' => 'MALTA',
                'nicename' => 'Malta',
                'iso3' => 'MLT',
                'numcode' => '470',
                'phone_code' => '356',
             ],
             [ 
             
                'id' => '133',
                'iso' => 'MH',
                'name' => 'MARSHALL ISLANDS',
                'nicename' => 'Marshall Islands',
                'iso3' => 'MHL',
                'numcode' => '584',
                'phone_code' => '692',
             ],
             [ 
             
                'id' => '134',
                'iso' => 'MQ',
                'name' => 'MARTINIQUE',
                'nicename' => 'Martinique',
                'iso3' => 'MTQ',
                'numcode' => '474',
                'phone_code' => '596',
             ],
             [ 
             
                'id' => '135',
                'iso' => 'MR',
                'name' => 'MAURITANIA',
                'nicename' => 'Mauritania',
                'iso3' => 'MRT',
                'numcode' => '478',
                'phone_code' => '222',
             ],
             [ 
             
                'id' => '136',
                'iso' => 'MU',
                'name' => 'MAURITIUS',
                'nicename' => 'Mauritius',
                'iso3' => 'MUS',
                'numcode' => '480',
                'phone_code' => '230',
             ],
             [ 
             
                'id' => '137',
                'iso' => 'YT',
                'name' => 'MAYOTTE',
                'nicename' => 'Mayotte',
                'iso3' => 'MYT',
                'numcode' => '175',
                'phone_code' => '269',
             ],
             [ 
             
                'id' => '138',
                'iso' => 'MX',
                'name' => 'MEXICO',
                'nicename' => 'Mexico',
                'iso3' => 'MEX',
                'numcode' => '484',
                'phone_code' => '52',
             ],
             [ 
             
                'id' => '139',
                'iso' => 'FM',
                'name' => 'MICRONESIA, FEDERATED STATES OF',
                'nicename' => 'Micronesia, Federated States of',
                'iso3' => 'FSM',
                'numcode' => '583',
                'phone_code' => '691',
             ],
             [ 
             
                'id' => '140',
                'iso' => 'MD',
                'name' => 'MOLDOVA, REPUBLIC OF',
                'nicename' => 'Moldova, Republic of',
                'iso3' => 'MDA',
                'numcode' => '498',
                'phone_code' => '373',
             ],
             [ 
             
                'id' => '141',
                'iso' => 'MC',
                'name' => 'MONACO',
                'nicename' => 'Monaco',
                'iso3' => 'MCO',
                'numcode' => '492',
                'phone_code' => '377',
             ],
             [ 
             
                'id' => '142',
                'iso' => 'MN',
                'name' => 'MONGOLIA',
                'nicename' => 'Mongolia',
                'iso3' => 'MNG',
                'numcode' => '496',
                'phone_code' => '976',
             ],
             [ 
             
                'id' => '143',
                'iso' => 'MS',
                'name' => 'MONTSERRAT',
                'nicename' => 'Montserrat',
                'iso3' => 'MSR',
                'numcode' => '500',
                'phone_code' => '1664',
             ],
             [ 
             
                'id' => '144',
                'iso' => 'MA',
                'name' => 'MOROCCO',
                'nicename' => 'Morocco',
                'iso3' => 'MAR',
                'numcode' => '504',
                'phone_code' => '212',
             ],
             [ 
             
                'id' => '145',
                'iso' => 'MZ',
                'name' => 'MOZAMBIQUE',
                'nicename' => 'Mozambique',
                'iso3' => 'MOZ',
                'numcode' => '508',
                'phone_code' => '258',
             ],
             [ 
             
                'id' => '146',
                'iso' => 'MM',
                'name' => 'MYANMAR',
                'nicename' => 'Myanmar',
                'iso3' => 'MMR',
                'numcode' => '104',
                'phone_code' => '95',
             ],
             [ 
             
                'id' => '147',
                'iso' => 'NA',
                'name' => 'NAMIBIA',
                'nicename' => 'Namibia',
                'iso3' => 'NAM',
                'numcode' => '516',
                'phone_code' => '264',
             ],
             [ 
             
                'id' => '148',
                'iso' => 'NR',
                'name' => 'NAURU',
                'nicename' => 'Nauru',
                'iso3' => 'NRU',
                'numcode' => '520',
                'phone_code' => '674',
             ],
             [ 
             
                'id' => '149',
                'iso' => 'NP',
                'name' => 'NEPAL',
                'nicename' => 'Nepal',
                'iso3' => 'NPL',
                'numcode' => '524',
                'phone_code' => '977',
             ],
             [ 
             
                'id' => '150',
                'iso' => 'NL',
                'name' => 'NETHERLANDS',
                'nicename' => 'Netherlands',
                'iso3' => 'NLD',
                'numcode' => '528',
                'phone_code' => '31',
             ],
             [ 
             
                'id' => '151',
                'iso' => 'AN',
                'name' => 'NETHERLANDS ANTILLES',
                'nicename' => 'Netherlands Antilles',
                'iso3' => 'ANT',
                'numcode' => '530',
                'phone_code' => '599',
             ],
             [ 
             
                'id' => '152',
                'iso' => 'NC',
                'name' => 'NEW CALEDONIA',
                'nicename' => 'New Caledonia',
                'iso3' => 'NCL',
                'numcode' => '540',
                'phone_code' => '687',
             ],
             [ 
             
                'id' => '153',
                'iso' => 'NZ',
                'name' => 'NEW ZEALAND',
                'nicename' => 'New Zealand',
                'iso3' => 'NZL',
                'numcode' => '554',
                'phone_code' => '64',
             ],
             [ 
             
                'id' => '154',
                'iso' => 'NI',
                'name' => 'NICARAGUA',
                'nicename' => 'Nicaragua',
                'iso3' => 'NIC',
                'numcode' => '558',
                'phone_code' => '505',
             ],
             [ 
             
                'id' => '155',
                'iso' => 'NE',
                'name' => 'NIGER',
                'nicename' => 'Niger',
                'iso3' => 'NER',
                'numcode' => '562',
                'phone_code' => '227',
             ],
             [ 
             
                'id' => '156',
                'iso' => 'NG',
                'name' => 'NIGERIA',
                'nicename' => 'Nigeria',
                'iso3' => 'NGA',
                'numcode' => '566',
                'phone_code' => '234',
             ],
             [ 
             
                'id' => '157',
                'iso' => 'NU',
                'name' => 'NIUE',
                'nicename' => 'Niue',
                'iso3' => 'NIU',
                'numcode' => '570',
                'phone_code' => '683',
             ],
             [ 
             
                'id' => '158',
                'iso' => 'NF',
                'name' => 'NORFOLK ISLAND',
                'nicename' => 'Norfolk Island',
                'iso3' => 'NFK',
                'numcode' => '574',
                'phone_code' => '672',
             ],
             [ 
             
                'id' => '159',
                'iso' => 'MP',
                'name' => 'NORTHERN MARIANA ISLANDS',
                'nicename' => 'Northern Mariana Islands',
                'iso3' => 'MNP',
                'numcode' => '580',
                'phone_code' => '1670',
             ],
             [ 
             
                'id' => '160',
                'iso' => 'NO',
                'name' => 'NORWAY',
                'nicename' => 'Norway',
                'iso3' => 'NOR',
                'numcode' => '578',
                'phone_code' => '47',
             ],
             [ 
             
                'id' => '161',
                'iso' => 'OM',
                'name' => 'OMAN',
                'nicename' => 'Oman',
                'iso3' => 'OMN',
                'numcode' => '512',
                'phone_code' => '968',
             ],
             [ 
             
                'id' => '162',
                'iso' => 'PK',
                'name' => 'PAKISTAN',
                'nicename' => 'Pakistan',
                'iso3' => 'PAK',
                'numcode' => '586',
                'phone_code' => '92',
             ],
             [ 
             
                'id' => '163',
                'iso' => 'PW',
                'name' => 'PALAU',
                'nicename' => 'Palau',
                'iso3' => 'PLW',
                'numcode' => '585',
                'phone_code' => '680',
             ],
             [ 
             
                'id' => '164',
                'iso' => 'PS',
                'name' => 'PALESTINIAN TERRITORY, OCCUPIED',
                'nicename' => 'Palestinian Territory, Occupied',
                'iso3' => 'PSE',
                'numcode' => '275',
                'phone_code' => '970',
             ],
             [ 
             
                'id' => '165',
                'iso' => 'PA',
                'name' => 'PANAMA',
                'nicename' => 'Panama',
                'iso3' => 'PAN',
                'numcode' => '591',
                'phone_code' => '507',
             ],
             [ 
             
                'id' => '166',
                'iso' => 'PG',
                'name' => 'PAPUA NEW GUINEA',
                'nicename' => 'Papua New Guinea',
                'iso3' => 'PNG',
                'numcode' => '598',
                'phone_code' => '675',
             ],
             [ 
             
                'id' => '167',
                'iso' => 'PY',
                'name' => 'PARAGUAY',
                'nicename' => 'Paraguay',
                'iso3' => 'PRY',
                'numcode' => '600',
                'phone_code' => '595',
             ],
             [ 
             
                'id' => '168',
                'iso' => 'PE',
                'name' => 'PERU',
                'nicename' => 'Peru',
                'iso3' => 'PER',
                'numcode' => '604',
                'phone_code' => '51',
             ],
             [ 
             
                'id' => '169',
                'iso' => 'PH',
                'name' => 'PHILIPPINES',
                'nicename' => 'Philippines',
                'iso3' => 'PHL',
                'numcode' => '608',
                'phone_code' => '63',
             ],
             [ 
             
                'id' => '170',
                'iso' => 'PN',
                'name' => 'PITCAIRN',
                'nicename' => 'Pitcairn',
                'iso3' => 'PCN',
                'numcode' => '612',
                'phone_code' => '0',
             ],
             [ 
             
                'id' => '171',
                'iso' => 'PL',
                'name' => 'POLAND',
                'nicename' => 'Poland',
                'iso3' => 'POL',
                'numcode' => '616',
                'phone_code' => '48',
             ],
             [ 
             
                'id' => '172',
                'iso' => 'PT',
                'name' => 'PORTUGAL',
                'nicename' => 'Portugal',
                'iso3' => 'PRT',
                'numcode' => '620',
                'phone_code' => '351',
             ],
             [ 
             
                'id' => '173',
                'iso' => 'PR',
                'name' => 'PUERTO RICO',
                'nicename' => 'Puerto Rico',
                'iso3' => 'PRI',
                'numcode' => '630',
                'phone_code' => '1787',
             ],
             [ 
                'id' => '174',
                'iso' => 'QA',
                'name' => 'QATAR',
                'nicename' => 'Qatar',
                'iso3' => 'QAT',
                'numcode' => '634',
                'phone_code' => '974',
             ],
             [ 
                'id' => '175',
                'iso' => 'RE',
                'name' => 'REUNION',
                'nicename' => 'Reunion',
                'iso3' => 'REU',
                'numcode' => '638',
                'phone_code' => '262',
             ],
             [ 
             
                'id' => '176',
                'iso' => 'RO',
                'name' => 'ROMANIA',
                'nicename' => 'Romania',
                'iso3' => 'ROM',
                'numcode' => '642',
                'phone_code' => '40',
             ],
             [ 
                'id' => '177',
                'iso' => 'RU',
                'name' => 'RUSSIAN FEDERATION',
                'nicename' => 'Russian Federation',
                'iso3' => 'RUS',
                'numcode' => '643',
                'phone_code' => '70',
             ],
             [ 
                'id' => '178',
                'iso' => 'RW',
                'name' => 'RWANDA',
                'nicename' => 'Rwanda',
                'iso3' => 'RWA',
                'numcode' => '646',
                'phone_code' => '250',
             ],
             [ 
             
                'id' => '179',
                'iso' => 'SH',
                'name' => 'SAINT HELENA',
                'nicename' => 'Saint Helena',
                'iso3' => 'SHN',
                'numcode' => '654',
                'phone_code' => '290',
            ],
            [
                'id' => '180',
                'iso' => 'KN',
                'name' => 'SAINT KITTS AND NEVIS',
                'nicename' => 'Saint Kitts and Nevis',
                'iso3' => 'KNA',
                'numcode' => '659',
                'phone_code' => '1869',
            ],
            [
                'id' => '181',
                'iso' => 'LC',
                'name' => 'SAINT LUCIA',
                'nicename' => 'Saint Lucia',
                'iso3' => 'LCA',
                'numcode' => '662',
                'phone_code' => '1758',
            ],
            [
                'id' => '182',
                'iso' => 'PM',
                'name' => 'SAINT PIERRE AND MIQUELON',
                'nicename' => 'Saint Pierre and Miquelon',
                'iso3' => 'SPM',
                'numcode' => '666',
                'phone_code' => '508',
            ],
            [
                'id' => '183',
                'iso' => 'VC',
                'name' => 'SAINT VINCENT AND THE GRENADINES',
                'nicename' => 'Saint Vincent and the Grenadines',
                'iso3' => 'VCT',
                'numcode' => '670',
                'phone_code' => '1784',
            ],
            [
                'id' => '184',
                'iso' => 'WS',
                'name' => 'SAMOA',
                'nicename' => 'Samoa',
                'iso3' => 'WSM',
                'numcode' => '882',
                'phone_code' => '684',
            ],
            [
                'id' => '185',
                'iso' => 'SM',
                'name' => 'SAN MARINO',
                'nicename' => 'San Marino',
                'iso3' => 'SMR',
                'numcode' => '674',
                'phone_code' => '378',
            ],
            [
                'id' => '186',
                'iso' => 'ST',
                'name' => 'SAO TOME AND PRINCIPE',
                'nicename' => 'Sao Tome and Principe',
                'iso3' => 'STP',
                'numcode' => '678',
                'phone_code' => '239',
            ],
            [
                'id' => '187',
                'iso' => 'SA',
                'name' => 'SAUDI ARABIA',
                'nicename' => 'Saudi Arabia',
                'iso3' => 'SAU',
                'numcode' => '682',
                'phone_code' => '966',
            ],
            [
                'id' => '188',
                'iso' => 'SN',
                'name' => 'SENEGAL',
                'nicename' => 'Senegal',
                'iso3' => 'SEN',
                'numcode' => '686',
                'phone_code' => '221',
            ],
            [
                'id' => '189',
                'iso' => 'CS',
                'name' => 'SERBIA AND MONTENEGRO',
                'nicename' => 'Serbia and Montenegro',
                'iso3' => 'SCG',
                'numcode' => '891',
                'phone_code' => '381',
            ],
            [
                'id' => '190',
                'iso' => 'SC',
                'name' => 'SEYCHELLES',
                'nicename' => 'Seychelles',
                'iso3' => 'SYC',
                'numcode' => '690',
                'phone_code' => '248',
            ],
            [
                'id' => '191',
                'iso' => 'SL',
                'name' => 'SIERRA LEONE',
                'nicename' => 'Sierra Leone',
                'iso3' => 'SLE',
                'numcode' => '694',
                'phone_code' => '232',
            ],
            [
                'id' => '192',
                'iso' => 'SG',
                'name' => 'SINGAPORE',
                'nicename' => 'Singapore',
                'iso3' => 'SGP',
                'numcode' => '702',
                'phone_code' => '65',
            ],
            [
                'id' => '193',
                'iso' => 'SK',
                'name' => 'SLOVAKIA',
                'nicename' => 'Slovakia',
                'iso3' => 'SVK',
                'numcode' => '703',
                'phone_code' => '421',
            ],
            [
                'id' => '194',
                'iso' => 'SI',
                'name' => 'SLOVENIA',
                'nicename' => 'Slovenia',
                'iso3' => 'SVN',
                'numcode' => '705',
                'phone_code' => '386',
            ],
            [
                'id' => '195',
                'iso' => 'SB',
                'name' => 'SOLOMON ISLANDS',
                'nicename' => 'Solomon Islands',
                'iso3' => 'SLB',
                'numcode' => '90',
                'phone_code' => '677',
            ],
            [
                'id' => '196',
                'iso' => 'SO',
                'name' => 'SOMALIA',
                'nicename' => 'Somalia',
                'iso3' => 'SOM',
                'numcode' => '706',
                'phone_code' => '252',
            ],
            [
                'id' => '197',
                'iso' => 'ZA',
                'name' => 'SOUTH AFRICA',
                'nicename' => 'South Africa',
                'iso3' => 'ZAF',
                'numcode' => '710',
                'phone_code' => '27',
            ],
            [
                'id' => '198',
                'iso' => 'GS',
                'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
                'nicename' => 'South Georgia and the South Sandwich Islands',
                'iso3' => 'SGS',
                'numcode' => '239',
                'phone_code' => '0',
            ],
            [
                'id' => '199',
                'iso' => 'ES',
                'name' => 'SPAIN',
                'nicename' => 'Spain',
                'iso3' => 'ESP',
                'numcode' => '724',
                'phone_code' => '34',
            ],
            [
                'id' => '200',
                'iso' => 'LK',
                'name' => 'SRI LANKA',
                'nicename' => 'Sri Lanka',
                'iso3' => 'LKA',
                'numcode' => '144',
                'phone_code' => '94',
            ],
            [
                'id' => '201',
                'iso' => 'SD',
                'name' => 'SUDAN',
                'nicename' => 'Sudan',
                'iso3' => 'SDN',
                'numcode' => '736',
                'phone_code' => '249',
            ],
            [
                'id' => '202',
                'iso' => 'SR',
                'name' => 'SURINAME',
                'nicename' => 'Suriname',
                'iso3' => 'SUR',
                'numcode' => '740',
                'phone_code' => '597',
            ],
            [
                'id' => '203',
                'iso' => 'SJ',
                'name' => 'SVALBARD AND JAN MAYEN',
                'nicename' => 'Svalbard and Jan Mayen',
                'iso3' => 'SJM',
                'numcode' => '744',
                'phone_code' => '47',
            ],
            [
                'id' => '204',
                'iso' => 'SZ',
                'name' => 'SWAZILAND',
                'nicename' => 'Swaziland',
                'iso3' => 'SWZ',
                'numcode' => '748',
                'phone_code' => '268',
            ],
            [
                'id' => '205',
                'iso' => 'SE',
                'name' => 'SWEDEN',
                'nicename' => 'Sweden',
                'iso3' => 'SWE',
                'numcode' => '752',
                'phone_code' => '46',
            ],
            [
                'id' => '206',
                'iso' => 'CH',
                'name' => 'SWITZERLAND',
                'nicename' => 'Switzerland',
                'iso3' => 'CHE',
                'numcode' => '756',
                'phone_code' => '41',
            ],
            [
                'id' => '207',
                'iso' => 'SY',
                'name' => 'SYRIAN ARAB REPUBLIC',
                'nicename' => 'Syrian Arab Republic',
                'iso3' => 'SYR',
                'numcode' => '760',
                'phone_code' => '963',
            ],
            [
                'id' => '208',
                'iso' => 'TW',
                'name' => 'TAIWAN, PROVINCE OF CHINA',
                'nicename' => 'Taiwan, Province of China',
                'iso3' => 'TWN',
                'numcode' => '158',
                'phone_code' => '886',
            ],
            [
                'id' => '209',
                'iso' => 'TJ',
                'name' => 'TAJIKISTAN',
                'nicename' => 'Tajikistan',
                'iso3' => 'TJK',
                'numcode' => '762',
                'phone_code' => '992',
            ],
            [
                'id' => '210',
                'iso' => 'TZ',
                'name' => 'TANZANIA, UNITED REPUBLIC OF',
                'nicename' => 'Tanzania, United Republic of',
                'iso3' => 'TZA',
                'numcode' => '834',
                'phone_code' => '255',
            ],
            [
                'id' => '211',
                'iso' => 'TH',
                'name' => 'THAILAND',
                'nicename' => 'Thailand',
                'iso3' => 'THA',
                'numcode' => '764',
                'phone_code' => '66',
            ],
            [
                'id' => '212',
                'iso' => 'TL',
                'name' => 'TIMOR-LESTE',
                'nicename' => 'Timor-Leste',
                'iso3' => 'TLS',
                'numcode' => '626',
                'phone_code' => '670',
            ],
            [
                'id' => '213',
                'iso' => 'TG',
                'name' => 'TOGO',
                'nicename' => 'Togo',
                'iso3' => 'TGO',
                'numcode' => '768',
                'phone_code' => '228',
            ],
            [
                'id' => '214',
                'iso' => 'TK',
                'name' => 'TOKELAU',
                'nicename' => 'Tokelau',
                'iso3' => 'TKL',
                'numcode' => '772',
                'phone_code' => '690',
            ],
            [
                'id' => '215',
                'iso' => 'TO',
                'name' => 'TONGA',
                'nicename' => 'Tonga',
                'iso3' => 'TON',
                'numcode' => '776',
                'phone_code' => '676',
            ],
            [
                'id' => '216',
                'iso' => 'TT',
                'name' => 'TRINIDAD AND TOBAGO',
                'nicename' => 'Trinidad and Tobago',
                'iso3' => 'TTO',
                'numcode' => '780',
                'phone_code' => '1868',
            ],
            [
                'id' => '217',
                'iso' => 'TN',
                'name' => 'TUNISIA',
                'nicename' => 'Tunisia',
                'iso3' => 'TUN',
                'numcode' => '788',
                'phone_code' => '216',
            ],
            [
                'id' => '218',
                'iso' => 'TR',
                'name' => 'TURKEY',
                'nicename' => 'Turkey',
                'iso3' => 'TUR',
                'numcode' => '792',
                'phone_code' => '90',
            ],
            [
                'id' => '219',
                'iso' => 'TM',
                'name' => 'TURKMENISTAN',
                'nicename' => 'Turkmenistan',
                'iso3' => 'TKM',
                'numcode' => '795',
                'phone_code' => '7370',
            ],
            [
                'id' => '220',
                'iso' => 'TC',
                'name' => 'TURKS AND CAICOS ISLANDS',
                'nicename' => 'Turks and Caicos Islands',
                'iso3' => 'TCA',
                'numcode' => '796',
                'phone_code' => '1649',
            ],
            [
                'id' => '221',
                'iso' => 'TV',
                'name' => 'TUVALU',
                'nicename' => 'Tuvalu',
                'iso3' => 'TUV',
                'numcode' => '798',
                'phone_code' => '688',
            ],
            [
                'id' => '222',
                'iso' => 'UG',
                'name' => 'UGANDA',
                'nicename' => 'Uganda',
                'iso3' => 'UGA',
                'numcode' => '800',
                'phone_code' => '256',
            ],
            [
                'id' => '223',
                'iso' => 'UA',
                'name' => 'UKRAINE',
                'nicename' => 'Ukraine',
                'iso3' => 'UKR',
                'numcode' => '804',
                'phone_code' => '380',
            ],
            [
                'id' => '224',
                'iso' => 'AE',
                'name' => 'UNITED ARAB EMIRATES',
                'nicename' => 'United Arab Emirates',
                'iso3' => 'ARE',
                'numcode' => '784',
                'phone_code' => '971',
            ],
            [
                'id' => '225',
                'iso' => 'GB',
                'name' => 'UNITED KINGDOM',
                'nicename' => 'United Kingdom',
                'iso3' => 'GBR',
                'numcode' => '826',
                'phone_code' => '44',
            ],
            [
                'id' => '226',
                'iso' => 'US',
                'name' => 'UNITED STATES',
                'nicename' => 'United States',
                'iso3' => 'USA',
                'numcode' => '840',
                'phone_code' => '1',
            ],
            [
                'id' => '227',
                'iso' => 'UM',
                'name' => 'UNITED STATES MINOR OUTLYING ISLANDS',
                'nicename' => 'United States Minor Outlying Islands',
                'iso3' => 'UMI',
                'numcode' => '581',
                'phone_code' => '1',
            ],
            [
                'id' => '228',
                'iso' => 'UY',
                'name' => 'URUGUAY',
                'nicename' => 'Uruguay',
                'iso3' => 'URY',
                'numcode' => '858',
                'phone_code' => '598',
            ],
            [
                'id' => '229',
                'iso' => 'UZ',
                'name' => 'UZBEKISTAN',
                'nicename' => 'Uzbekistan',
                'iso3' => 'UZB',
                'numcode' => '860',
                'phone_code' => '998',
            ],
            [
                'id' => '230',
                'iso' => 'VU',
                'name' => 'VANUATU',
                'nicename' => 'Vanuatu',
                'iso3' => 'VUT',
                'numcode' => '548',
                'phone_code' => '678',
            ],
            [ 
                'id' => '231',
                'iso' => 'VE',
                'name' => 'VENEZUELA',
                'nicename' => 'Venezuela',
                'iso3' => 'VEN',
                'numcode' => '862',
                'phone_code' => '58',
            ],
            [
                'id' => '232',
                'iso' => 'VN',
                'name' => 'VIET NAM',
                'nicename' => 'Viet Nam',
                'iso3' => 'VNM',
                'numcode' => '704',
                'phone_code' => '84',
            ],
            [
                'id' => '233',
                'iso' => 'VG',
                'name' => 'VIRGIN ISLANDS, BRITISH',
                'nicename' => 'Virgin Islands, British',
                'iso3' => 'VGB',
                'numcode' => '92',
                'phone_code' => '1284',
            ],
            [
                'id' => '234',
                'iso' => 'VI',
                'name' => 'VIRGIN ISLANDS, U.S.',
                'nicename' => 'Virgin Islands, U.s.',
                'iso3' => 'VIR',
                'numcode' => '850',
                'phone_code' => '1340',
            ],
            [
                'id' => '235',
                'iso' => 'WF',
                'name' => 'WALLIS AND FUTUNA',
                'nicename' => 'Wallis and Futuna',
                'iso3' => 'WLF',
                'numcode' => '876',
                'phone_code' => '681',
            ],
            [
                'id' => '236',
                'iso' => 'EH',
                'name' => 'WESTERN SAHARA',
                'nicename' => 'Western Sahara',
                'iso3' => 'ESH',
                'numcode' => '732',
                'phone_code' => '212',
            ],
            [
                'id' => '237',
                'iso' => 'YE',
                'name' => 'YEMEN',
                'nicename' => 'Yemen',
                'iso3' => 'YEM',
                'numcode' => '887',
                'phone_code' => '967',
            ],
            [
                'id' => '238',
                'iso' => 'ZM',
                'name' => 'ZAMBIA',
                'nicename' => 'Zambia',
                'iso3' => 'ZMB',
                'numcode' => '894',
                'phone_code' => '260',
            ],
            [  
                'id' => '239',
                'iso' => 'ZW',
                'name' => 'ZIMBABWE',
                'nicename' => 'Zimbabwe',
                'iso3' => 'ZWE',
                'numcode' => '716',
                'phone_code' => '263',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
